# Generated by Django 4.2.11 on 2024-05-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminhome', '0050_remove_poojatype_model_photo'),
        ('Devotee', '0021_alter_payment_model_total_amount'),
        ('Registration', '0007_alter_enquiry_model_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='income_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('Amount', models.IntegerField()),
                ('Narration', models.CharField(max_length=30)),
                ('Bookingpooja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devotee.bookingpooja_model')),
                ('Devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.devotee_model')),
                ('income_typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.income_model')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.staff_model')),
            ],
            options={
                'db_table': 'Income_model',
            },
        ),
    ]
