# Generated by Django 4.2 on 2025-02-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0066_staff_model_temple_name'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes_models',
            name='Temp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.templeinfo_model'),
        ),
    ]
