# Generated by Django 4.2.11 on 2024-05-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_alter_enquiry_model_query'),
        ('Devotee', '0021_alter_payment_model_total_amount'),
        ('staff', '0002_rename_income_model_incomes_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes_model',
            name='Bookingpooja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Devotee.bookingpooja_model'),
        ),
        migrations.AlterField(
            model_name='incomes_model',
            name='Devotee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.devotee_model'),
        ),
    ]
