# Generated by Django 4.2 on 2025-03-02 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0074_alter_pooja_model_desc'),
        ('staff', '0002_incomes_models_temp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_date', models.DateTimeField(default=django.utils.timezone.now, max_length=10)),
                ('Amount', models.IntegerField()),
                ('Narration', models.TextField(max_length=30, null=True)),
                ('Expense_typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.expense_model')),
                ('Temple_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.templeinfo_model')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.staff_model')),
            ],
            options={
                'db_table': 'Staff_Expense_model',
            },
        ),
    ]
