# Generated by Django 4.2.11 on 2024-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_incomes_model_bookingpooja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes_model',
            name='Narration',
            field=models.TextField(max_length=30),
        ),
    ]
