# Generated by Django 4.2.11 on 2024-05-14 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0050_remove_poojatype_model_photo'),
        ('staff', '0004_alter_incomes_model_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes_model',
            name='Narration',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='incomes_model',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.staff_model'),
        ),
    ]
