# Generated by Django 4.2.11 on 2024-05-14 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_incomes_model_narration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes_model',
            name='income_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=10),
        ),
    ]
