from django.urls import path
from . import views


urlpatterns = [
    path('',views.home,name='home'),
    path('insert_district',views.insert_district,name='distname'),
    path('insert_location',views.insert_location,name='locname'),
    path('insert_staff', views.insert_staff, name='staff'),
    path('insert_templeinfo',views.insert_templeinfo,name='templeinfo'),
    path('insert_priest',views.insert_priest,name='Pname'),
    path('insert_pooja',views.insert_pooja,name='pooja'),
    path('insert_day',views.insert_day,name='day'),
    path('insert_transf',views.insert_transf,name='trans'),
    path('insert_income',views.insert_income,name='income'),
    path('update_district/<did>',views.update_district,name='up_district'),
    path('delete_district/<did>',views.delete_district,name='dele_district'),
    path('update_location/<lid>',views.update_location,name='up_location'),
    path('delete_location/<lid>',views.delete_location,name='dele_location'),
    path('update_staff/<sid>', views.update_staff, name='up_staff'),
    path('delete_staff/<sid>', views.delete_staff, name='dele_staff'),
    path('update_templeinfo/<tid>', views.update_templeinfo, name='up_temple'),
    path('delete_templeinfo/<tid>', views.delete_templeinfo, name='dele_temple'),
    path('update_priest/<pid>', views.update_priest, name='up_priest'),
    path('delete_priest/<pid>', views.delete_priest, name='dele_priest'),
    path('update_pooja/<pid>', views.update_pooja, name='up_pooja'),
    path('delete_pooja/<pid>', views.delete_pooja, name='dele_pooja'),
    path('insert_month',views.insert_month,name='month'),
    path('update_day/<did>', views.update_day, name='up_day'),
    path('delete_day/<did>', views.delete_day, name='dele_day'),
    path('update_month/<mid>', views.update_month, name='up_month'),
    path('delete_month/<mid>', views.delete_month, name='dele_month'),
    path('update_trans/<tid>', views.update_trans, name='up_trans'),
    path('delete_trans/<tid>', views.delete_trans, name='dele_trans'),
    path('update_income/<iid>', views.update_income, name='up_income'),
    path('delete_income/<iid>', views.delete_income, name='dele_income'),
    path('insert_expense',views.insert_expense,name='expense'),
    path('update_expense/<eid>', views.update_expense, name='up_expense'),
    path('delete_expense/<eid>', views.delete_expense, name='dele_expense'),
    path('insert_special', views.insert_special, name='special'),
    path('insert_schedule', views.insert_schedule, name='schedule'),
    path('insert_careers',views.insert_careers,name='careers'),
    path('update_schedule/<sid>', views.update_schedule, name='up_sche'),
    path('delete_schedule/<sid>', views.delete_schedule, name='dele_sche'),
    path('update_special/<sid>', views.update_special, name='up_special'),
    path('delete_special/<sid>', views.delete_special, name='dele_special'),
    path('update_careers/<cid>', views.update_careers, name='up_care'),
    path('delete_careers/<cid>', views.delete_careers, name='dele_care'),
    path('insert_darshan', views.insert_darshan, name='darshan'),
    path('update_darshan/<did>', views.update_darshan, name='up_dars'),
    path('delete_darshan/<did>', views.delete_darshan, name='dele_dars'),
    # path('show_enquiry/', views.show_enquiry, name='enquiry'),
    path('delete_enquiry/<eid>', views.delete_enquiry, name='dele_enq'),
    path('view_enquiry',views.view_enquiry,name='enquiry'),
    path('more_enquiry/<enid>',views.more_enquiry,name='more_enq'),
    path('activate_enquiry/<enid>', views.activate_enquiry, name='activate_enquiry'),

]