# Generated by Django 4.2.11 on 2024-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_model',
            name='Application_date',
            field=models.DateTimeField(default='Inactive', max_length=10),
        ),
    ]
