# Generated by Django 4.2.11 on 2024-04-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0049_pooja_model_photo'),
        ('Registration', '0007_alter_enquiry_model_query'),
        ('Devotee', '0004_alter_application_model_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='poojabook_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('star', models.CharField(max_length=30)),
                ('Status', models.CharField(default='cart', max_length=30)),
                ('Devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.devotee_model')),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.pooja_model')),
            ],
            options={
                'db_table': 'Pooja_Book',
            },
        ),
    ]
