# Generated by Django 4.2.11 on 2024-04-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0049_pooja_model_photo'),
        ('Devotee', '0006_alter_poojabook_model_pooja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojabook_model',
            name='pooja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.pooja_model'),
        ),
    ]
