# Generated by Django 4.2.11 on 2024-05-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0050_remove_poojatype_model_photo'),
        ('Registration', '0007_alter_enquiry_model_query'),
        ('Devotee', '0008_alter_poojabook_model_pooja'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingpooja_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_type', models.CharField(default='online', max_length=30)),
                ('Want_date', models.DateTimeField(max_length=10)),
                ('booked_date', models.DateTimeField(max_length=10)),
                ('Total_amount', models.IntegerField()),
                ('Status', models.CharField(default='Active', max_length=30)),
                ('Devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.devotee_model')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.staff_model')),
            ],
            options={
                'db_table': 'Bokking_Pooja',
            },
        ),
    ]
