# Generated by Django 4.2.11 on 2024-05-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0050_remove_poojatype_model_photo'),
        ('Devotee', '0009_bookingpooja_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpooja_model',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.staff_model'),
        ),
    ]
