# Generated by Django 4.2.11 on 2024-05-01 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0010_alter_bookingpooja_model_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpooja_model',
            name='booked_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=10),
        ),
    ]
