# Generated by Django 4.2.11 on 2024-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0011_alter_bookingpooja_model_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpooja_model',
            name='Want_date',
            field=models.DateField(),
        ),
    ]
