# Generated by Django 4.2.11 on 2024-05-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0012_alter_bookingpooja_model_want_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_date', models.DateField()),
                ('card_type', models.CharField(max_length=30)),
                ('card_holder_name', models.CharField(max_length=30)),
                ('Card_number', models.IntegerField()),
                ('card_exp_date', models.DateField()),
                ('cvv_number', models.IntegerField()),
                ('Status', models.CharField(default='Active', max_length=30)),
                ('Total_amount', models.IntegerField()),
                ('poojabookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devotee.bookingpooja_model')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
