# Generated by Django 4.2.11 on 2024-05-06 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0050_remove_poojatype_model_photo'),
        ('Devotee', '0013_payment_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_model',
            old_name='poojabookid',
            new_name='poojabook',
        ),
        migrations.AddField(
            model_name='payment_model',
            name='paymentmode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.transtype_model'),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='Payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='Status',
            field=models.CharField(default='paid', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='cvv_number',
            field=models.CharField(max_length=3),
        ),
    ]
