# Generated by Django 4.2.11 on 2024-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0014_rename_poojabookid_payment_model_poojabook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='card_type',
            field=models.CharField(choices=[('select', 'SELECT'), ('credit card', 'CREDIT CARD'), ('debit card', 'DEBIT CARD'), ('upi', 'UPI'), ('netbanking', 'NETBANKING')], default='SELECT', max_length=20),
        ),
    ]
