# Generated by Django 4.2.11 on 2024-05-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0015_alter_payment_model_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_model',
            name='paymentmode',
        ),
    ]
