# Generated by Django 4.2.11 on 2024-05-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0016_remove_payment_model_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='Total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
