# Generated by Django 4.2.11 on 2024-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0021_alter_payment_model_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='Card_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='card_exp_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='cvv_number',
            field=models.IntegerField(max_length=3),
        ),
    ]
