# Generated by Django 4.2.11 on 2024-08-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0022_alter_payment_model_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='cvv_number',
            field=models.IntegerField(),
        ),
    ]
