# Generated by Django 4.2.11 on 2024-08-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0023_alter_payment_model_cvv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='card_exp_date',
            field=models.CharField(max_length=15),
        ),
    ]
