# Generated by Django 4.2.11 on 2024-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0024_alter_payment_model_card_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpooja_model',
            name='Status',
            field=models.CharField(default='New', max_length=30),
        ),
    ]
