# Generated by Django 4.2.11 on 2024-09-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0025_alter_bookingpooja_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojabook_model',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Devotee.bookingpooja_model'),
        ),
    ]
