# Generated by Django 4.2.11 on 2024-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0026_poojabook_model_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpooja_model',
            name='Total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingpooja_model',
            name='Want_date',
            field=models.DateField(null=True),
        ),
    ]
