# Generated by Django 4.2.11 on 2024-09-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devotee', '0028_alter_poojabook_model_pooja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojabook_model',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
