# Generated by Django 4.2.11 on 2024-03-19 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminhome', '0031_delete_devoteereg_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='devotee_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('photo', models.FileField(blank=True, upload_to='photos')),
                ('star', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Id')),
                ('mobile', models.BigIntegerField()),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.location_model')),
                ('login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
