# Generated by Django 4.2.11 on 2024-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_role_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email Id')),
                ('Mobile', models.BigIntegerField()),
                ('Query', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Enquiry',
            },
        ),
    ]
