# Generated by Django 4.2.11 on 2024-03-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_alter_enquiry_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_model',
            name='Status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
