# Generated by Django 4.2 on 2025-03-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_remove_devotee_model_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devotee_model',
            name='star',
        ),
    ]
