# Generated by Django 4.2.11 on 2024-03-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locname', models.CharField(max_length=30)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.distric_model')),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
