# Generated by Django 4.2.11 on 2024-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0002_location_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Id')),
                ('mobile', models.IntegerField()),
                ('photo', models.FileField(blank=True, upload_to='photos')),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
