# Generated by Django 4.2.11 on 2024-03-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0003_staff_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_model',
            name='address',
            field=models.TextField(max_length=40),
        ),
        migrations.CreateModel(
            name='templeinfo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('cotname', models.CharField(max_length=30)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.location_model')),
            ],
            options={
                'db_table': 'templeinfo',
            },
        ),
    ]
