# Generated by Django 4.2.11 on 2024-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0004_alter_staff_model_address_templeinfo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templeinfo_model',
            name='discription',
            field=models.TextField(max_length=100),
        ),
    ]
