# Generated by Django 4.2.11 on 2024-03-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0007_devoteereg_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='pooja_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poojatypeid', models.IntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=40)),
                ('amount', models.IntegerField()),
                ('active', models.CharField(max_length=30)),
                ('priestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminhome.priest_model')),
            ],
            options={
                'db_table': 'pooja_type',
            },
        ),
    ]
