# Generated by Django 4.2.11 on 2024-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0008_pooja_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='day_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(max_length=30)),
            ],
            options={
                'db_table': 'day',
            },
        ),
    ]
