# Generated by Django 4.2.11 on 2024-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0009_day_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='transtype_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transfer_type',
            },
        ),
        migrations.AlterField(
            model_name='day_model',
            name='day',
            field=models.DateTimeField(max_length=30),
        ),
    ]
