# Generated by Django 4.2.11 on 2024-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0010_transtype_model_alter_day_model_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='income_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inctype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'income_type',
            },
        ),
    ]
