# Generated by Django 4.2.11 on 2024-03-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0011_income_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_model',
            old_name='dist',
            new_name='District',
        ),
    ]
