# Generated by Django 4.2.11 on 2024-03-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0012_rename_dist_location_model_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_model',
            old_name='District',
            new_name='dist',
        ),
        migrations.AlterField(
            model_name='devoteereg_model',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pooja_model',
            name='desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='priest_model',
            name='Address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
