# Generated by Django 4.2.11 on 2024-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0013_rename_district_location_model_dist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Month',
            },
        ),
        migrations.AlterField(
            model_name='day_model',
            name='day',
            field=models.CharField(max_length=30),
        ),
    ]
