# Generated by Django 4.2.11 on 2024-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0016_poojaschedule_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojaschedule_model',
            name='Timings',
            field=models.DateField(max_length=8),
        ),
    ]
