# Generated by Django 4.2.11 on 2024-03-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0017_alter_poojaschedule_model_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialday_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('From_date', models.DateField(max_length=100)),
                ('To_date', models.DateField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'special_day',
            },
        ),
    ]
