# Generated by Django 4.2.11 on 2024-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0020_alter_enquiry_model_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='careers_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Refno', models.IntegerField(max_length=4)),
                ('Jobtitle', models.CharField(max_length=30)),
                ('Notification', models.CharField(max_length=30)),
                ('notifyfile', models.CharField(max_length=50)),
                ('adddate', models.CharField(max_length=50)),
                ('Status', models.CharField(default='inactive', max_length=50)),
            ],
            options={
                'db_table': 'careers',
            },
        ),
    ]
