# Generated by Django 4.2.11 on 2024-03-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0021_careers_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_model',
            name='Refno',
            field=models.IntegerField(),
        ),
    ]
