# Generated by Django 4.2.11 on 2024-03-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0022_alter_careers_model_refno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday_model',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
