# Generated by Django 4.2.11 on 2024-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0023_alter_specialday_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday_model',
            name='From_date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='specialday_model',
            name='To_date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='specialday_model',
            name='status',
            field=models.CharField(choices=[('select', 'SELECT'), ('active', 'Active'), ('inactive', 'Inactive')], default='SELECT', max_length=30),
        ),
    ]
