# Generated by Django 4.2.11 on 2024-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0024_alter_specialday_model_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday_model',
            name='To_date',
            field=models.DateTimeField(max_length=10),
        ),
    ]
