# Generated by Django 4.2.11 on 2024-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0025_alter_specialday_model_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_model',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
