# Generated by Django 4.2.11 on 2024-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0026_alter_enquiry_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojaschedule_model',
            name='Timings',
            field=models.CharField(max_length=8),
        ),
    ]
