# Generated by Django 4.2.11 on 2024-03-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0029_alter_poojaschedule_model_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojaschedule_model',
            name='Timings',
            field=models.CharField(max_length=8),
        ),
    ]
