# Generated by Django 4.2.11 on 2024-03-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0031_delete_devoteereg_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enquiry_model',
        ),
    ]
