# Generated by Django 4.2.11 on 2024-03-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0033_enquiry_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enquiry_model',
        ),
    ]
