# Generated by Django 4.2.11 on 2024-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0034_delete_enquiry_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='darshan_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_id', models.IntegerField()),
                ('Timings', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'darshan_timing',
            },
        ),
    ]
