# Generated by Django 4.2.11 on 2024-03-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0035_darshan_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darshan_model',
            name='Date_id',
        ),
    ]
