# Generated by Django 4.2.11 on 2024-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0036_remove_darshan_model_date_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='templeinfo_model',
            name='Photo',
            field=models.FileField(blank=True, upload_to='photos'),
        ),
    ]
