# Generated by Django 4.2.11 on 2024-03-28 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adminhome', '0037_templeinfo_model_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_model',
            name='login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
