# Generated by Django 4.2.11 on 2024-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0038_staff_model_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday_model',
            name='status',
            field=models.CharField(default='Inactive', max_length=30),
        ),
    ]
