# Generated by Django 4.2.11 on 2024-04-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0043_alter_careers_model_adddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_model',
            name='Status',
            field=models.CharField(max_length=50),
        ),
    ]
