# Generated by Django 4.2.11 on 2024-04-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0046_remove_pooja_model_poojatypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja_model',
            name='poojatypeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.poojatype_model'),
        ),
    ]
