# Generated by Django 4.2.11 on 2024-04-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0047_pooja_model_poojatypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojatype_model',
            name='Photo',
            field=models.FileField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='poojatype_model',
            name='Pooja_type',
            field=models.CharField(max_length=20),
        ),
    ]
