# Generated by Django 4.2.11 on 2024-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0048_poojatype_model_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja_model',
            name='Photo',
            field=models.FileField(blank=True, upload_to='photos'),
        ),
    ]
