# Generated by Django 4.2.11 on 2024-04-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0049_pooja_model_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poojatype_model',
            name='Photo',
        ),
    ]
