# Generated by Django 4.2.11 on 2024-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0050_remove_poojatype_model_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_model',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
