# Generated by Django 4.2.11 on 2024-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0051_alter_staff_model_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday_model',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
