# Generated by Django 4.2.11 on 2024-09-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0052_alter_specialday_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday_model',
            name='To_date',
            field=models.DateField(max_length=10),
        ),
    ]
