# Generated by Django 4.2.11 on 2024-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0054_alter_specialday_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templeinfo_model',
            name='discription',
            field=models.TextField(max_length=200),
        ),
    ]
