# Generated by Django 4.2.11 on 2024-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0055_alter_templeinfo_model_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='templeinfo_model',
            name='Pooja',
            field=models.ManyToManyField(to='Adminhome.pooja_model'),
        ),
    ]
