# Generated by Django 4.2.11 on 2024-10-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0057_rename_adddate_careers_model_adddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_model',
            name='Notification_file',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
