# Generated by Django 4.2.11 on 2024-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0058_alter_careers_model_notification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers_model',
            name='Notification_file',
            field=models.FileField(blank=True, upload_to='photos'),
        ),
    ]
