# Generated by Django 4.2.11 on 2024-10-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0059_alter_careers_model_notification_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojaschedule_model',
            name='Temple_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.templeinfo_model'),
        ),
    ]
