# Generated by Django 4.2.11 on 2024-10-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0064_alter_darshan_model_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='darshan_model',
            name='Day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.day_model'),
        ),
    ]
