# Generated by Django 4.2 on 2025-02-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0065_darshan_model_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_model',
            name='Temple_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.templeinfo_model'),
        ),
    ]
