# Generated by Django 4.2 on 2025-02-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0067_alter_pooja_model_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templeinfo_model',
            name='contnum',
            field=models.BigIntegerField(null=True),
        ),
    ]
