# Generated by Django 4.2 on 2025-02-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0068_templeinfo_model_contnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='priest_model',
            name='dist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.distric_model'),
        ),
    ]
