# Generated by Django 4.2 on 2025-02-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0069_priest_model_dist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest_model',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='priest_model',
            name='loc',
        ),
    ]
