# Generated by Django 4.2 on 2025-02-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0070_remove_priest_model_email_remove_priest_model_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='templeinfo_model',
            name='dist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.distric_model'),
        ),
    ]
