# Generated by Django 4.2 on 2025-02-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0071_templeinfo_model_dist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templeinfo_model',
            old_name='dist',
            new_name='Ditrict',
        ),
    ]
