# Generated by Django 4.2 on 2025-02-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0072_rename_dist_templeinfo_model_ditrict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templeinfo_model',
            name='Ditrict',
        ),
    ]
