# Generated by Django 4.2 on 2025-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0073_remove_templeinfo_model_ditrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja_model',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
