# Generated by Django 4.2 on 2025-03-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0074_alter_pooja_model_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooja_model',
            name='priestid',
        ),
    ]
