# Generated by Django 4.2 on 2025-03-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0075_remove_pooja_model_priestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='templeinfo_model',
            name='Priest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.priest_model'),
        ),
    ]
