# Generated by Django 4.2 on 2025-03-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminhome', '0076_templeinfo_model_priest'),
    ]

    operations = [
        migrations.AddField(
            model_name='templeinfo_model',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminhome.distric_model'),
        ),
    ]
